export const CARD_STYLE = `
:host{display:block;min-width:0;font-family:var(--ha-font-family-body,inherit);color:var(--primary-text-color)}
*{box-sizing:border-box}button{font:inherit;cursor:pointer}button:focus-visible,input:focus-visible{outline:2px solid var(--primary-color,#03a9f4);outline-offset:3px}button:disabled{cursor:default;opacity:.5}
ha-card{display:block;position:relative;height:212px;overflow:hidden;border-radius:16px;background:var(--ha-card-background,var(--card-background-color,#27313b));isolation:isolate}
:host ha-card::before{content:none}
ha-card[data-lit=true]{outline:3px solid #ffca28;outline-offset:-2px;box-shadow:0 0 0 2px #ffca28cc,0 0 16px #ffca28e6,0 0 32px #ffca28a6,0 0 48px #ffca2859}
.background{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-2}.shade{position:absolute;inset:0;background:linear-gradient(180deg,#0009 0%,#0002 40%,transparent 65%,#0002 100%);z-index:-1}
.heading{position:absolute;inset:12px 12px auto;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:start}.room-summary{min-width:0}.room-button{display:flex;align-items:center;gap:8px;width:100%;border:0;background:none;padding:0;color:white;text-align:left;font-size:14px;font-weight:600;text-shadow:0 1px 3px #0009;min-width:0}.room-button ha-icon{--mdc-icon-size:20px;flex-shrink:0}.name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.readings{margin:4px 0 0 28px;display:flex;flex-wrap:wrap;gap:0 6px;font-size:12px;color:#fff;line-height:18px;text-shadow:0 1px 3px #0009}.reading{padding:0;border:0;background:none;color:inherit;font:inherit;white-space:nowrap}.reading+.reading::before{content:'|';margin-right:6px;opacity:.7}
.status-row{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:4px;max-width:168px}.warnings,.sensor-status{display:flex;gap:4px}.warnings:empty,.sensor-status:empty,.sensor-status[hidden],.sensor-indicator[hidden]{display:none}
.warning,.sensor-indicator{width:24px;height:24px;padding:0;border:0;border-radius:6px;display:grid;place-items:center;flex-shrink:0}.warning{background:#e3f2fd;color:#087cca}.warning ha-icon,.sensor-indicator ha-icon{--mdc-icon-size:18px}.warning[data-kind=temperature_high]{background:#fff3e0;color:#c65d00}.warning[data-kind=humidity_low]{background:#fff8e1;color:#9c6500}
.sensor-indicator{position:relative;background:#eceff1;color:#7d858b}.sensor-indicator[data-active=true]{background:#ffe4e6;color:#a86070}.sensor-indicator[data-unavailable=true]{background:#e2e8f0;color:#64748b}.sensor-indicator .unavailable-dot{top:-3px;right:-3px;width:10px;height:10px;line-height:10px;font-size:8px}
.tiles{position:absolute;left:10px;right:10px;bottom:10px;display:flex;flex-wrap:nowrap;justify-content:flex-end;gap:6px;align-items:end}.tiles[data-alignment=left]{justify-content:flex-start}.tiles[data-alignment=center]{justify-content:center}.tile{flex:0 1 56px;width:56px;height:56px;min-width:0;display:grid;place-items:center;position:relative;padding:6px;border:var(--ha-card-border,1px solid #ffffff66);border-radius:12px;background:#ffffff80;backdrop-filter:var(--ha-card-backdrop-filter,blur(10px) saturate(1.25));-webkit-backdrop-filter:var(--ha-card-backdrop-filter,blur(10px) saturate(1.25));box-shadow:var(--ha-card-glass-inset-shadow,none);color:#888}.tile ha-icon{--mdc-icon-size:28px;stroke:#fff;stroke-width:1.5px;stroke-linejoin:round;paint-order:stroke fill}.tile[data-active=true]{color:#ffca28}.tile[data-unavailable=true]{color:#64748b}.unavailable-dot{position:absolute;top:5px;right:5px;width:12px;height:12px;border-radius:50%;background:#455a64;color:white;font-size:10px;line-height:12px;text-align:center}.unavailable-dot[hidden]{display:none}
.message{position:absolute;left:12px;right:12px;bottom:14px;color:#fff;font-size:12px;text-shadow:0 1px 3px #000}.message[hidden]{display:none}ha-card[data-has-controls=true] .message{bottom:76px}
dialog{padding:0;border:1px solid var(--divider-color,#ddd);border-radius:20px;background:var(--card-background-color,#fff);color:var(--primary-text-color,#222);width:min(500px,calc(100vw - 32px));max-height:85dvh;overflow:hidden;box-shadow:0 16px 64px #0006}dialog::backdrop{background:#0007;backdrop-filter:blur(4px)}
.dialog-header{display:flex;align-items:center;gap:12px;padding:18px 20px;border-bottom:1px solid var(--divider-color,#ddd)}.dialog-heading{flex:1;margin:0;font-size:18px;font-weight:600}.close{border:0;background:none;color:inherit;border-radius:50%;padding:8px;display:grid;place-items:center}.close ha-icon{--mdc-icon-size:22px}.dialog-body{max-height:calc(85dvh - 78px);overflow:auto;padding:8px 20px 20px;overscroll-behavior:contain}.group-title{margin:16px 0 6px;font-size:14px;color:var(--secondary-text-color,#666)}.entity-row{padding:10px 0;border-bottom:1px solid var(--divider-color,#eee);display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center}.entity-details{border:0;background:none;color:inherit;padding:4px 0;display:flex;align-items:center;gap:12px;min-width:0;text-align:left}.entity-details ha-icon{--mdc-icon-size:24px;color:var(--secondary-text-color,#666);flex-shrink:0}.entity-text{min-width:0}.entity-name{display:block;overflow-wrap:anywhere;font-size:14px}.entity-state{display:block;margin-top:3px;font-size:12px;color:var(--secondary-text-color,#666)}.entity-action{min-width:58px;min-height:36px;border:1px solid var(--divider-color,#ddd);border-radius:10px;background:var(--secondary-background-color,#eee);color:inherit;font-size:12px}.entity-action[data-on=true]{background:var(--primary-color,#03a9f4);color:var(--text-primary-color,#fff);border-color:transparent}.brightness{grid-column:1/-1;width:100%;accent-color:var(--primary-color,#03a9f4)}.dialog-error{color:var(--error-color,#db4437);font-size:13px;margin:8px 0}.dialog-error:empty{display:none}.empty{font-size:14px;color:var(--secondary-text-color,#666);padding:16px 0}
.entity-state[hidden]{display:none}.entity-details ha-icon[data-on=true]{color:var(--state-light-active-color,#ffca28);filter:drop-shadow(0 0 5px #ffca2859)}
.entity-toggle{position:relative;width:58px;min-height:40px;border:0;border-radius:20px;padding:0;background:none;color:inherit;flex-shrink:0}
.entity-toggle::before{content:'';position:absolute;inset:6px 2px;border:1px solid var(--divider-color,#bbb);border-radius:20px;background:var(--secondary-background-color,#ddd);transition:background .18s}
.toggle-thumb{position:absolute;top:10px;left:6px;width:20px;height:20px;border-radius:50%;background:var(--secondary-text-color,#777);box-shadow:0 1px 3px #0003;transition:transform .18s,background .18s;pointer-events:none}
.entity-toggle[data-on=true]::before{background:var(--primary-color,#03a9f4);border-color:transparent}.entity-toggle[data-on=true] .toggle-thumb{transform:translateX(26px);background:var(--text-primary-color,#fff)}
.entity-toggle[aria-busy=true]{cursor:progress}
.light-control{grid-column:1/-1;display:grid;grid-template-columns:1fr auto;gap:0 12px;align-items:center;min-width:0;padding:2px 0}
.control-label,.control-value{font-size:12px;color:var(--secondary-text-color,#666)}.control-value{display:flex;align-items:center;gap:6px;font-variant-numeric:tabular-nums}
.light-slider{grid-column:1/-1;appearance:none;-webkit-appearance:none;width:100%;min-width:0;height:38px;margin:0;padding:0 10px;border:0;background:transparent;cursor:pointer;--slider-gradient:linear-gradient(90deg,#161616,var(--light-color,#fff))}
.light-slider.color{--slider-gradient:linear-gradient(90deg,#f00 0%,#ff0 16.67%,#0f0 33.33%,#0ff 50%,#00f 66.67%,#f0f 83.33%,#f00 100%)}
.light-slider.temperature{--slider-gradient:linear-gradient(90deg,#ffad55,#fff2dd,#d6e9ff,#86bcff)}
.light-slider::-webkit-slider-runnable-track{height:16px;border-radius:8px;background:var(--slider-gradient);box-shadow:inset 0 0 0 1px #8885}
.light-slider::-moz-range-track{height:16px;border-radius:8px;background:var(--slider-gradient);box-shadow:inset 0 0 0 1px #8885}
.light-slider::-webkit-slider-thumb{appearance:none;-webkit-appearance:none;width:24px;height:24px;margin-top:-4px;border:3px solid #fff;border-radius:50%;background:var(--light-color,#eee);box-shadow:0 1px 5px #0008}
.light-slider::-moz-range-thumb{width:18px;height:18px;border:3px solid #fff;border-radius:50%;background:var(--light-color,#eee);box-shadow:0 1px 5px #0008}
.light-slider.color::-webkit-slider-thumb{background:var(--swatch-color,var(--light-color,#eee))}.light-slider:disabled{opacity:.4;cursor:default}
ha-card[data-has-image=false] .shade{display:none}
ha-card[data-has-image=false] .room-button{color:var(--primary-text-color,#222);text-shadow:none}
ha-card[data-has-image=false] .readings,ha-card[data-has-image=false] .message{color:var(--secondary-text-color,#666);text-shadow:none}
ha-card[data-has-image=false] .tile{background:var(--secondary-background-color,#e8eef3);border:1px solid var(--divider-color,#ddd);backdrop-filter:none;-webkit-backdrop-filter:none}
ha-card[data-has-image=false] .tile ha-icon{stroke:none}
@media(prefers-reduced-motion:reduce){.entity-toggle::before,.toggle-thumb{transition:none}}
@media(max-width:480px){dialog{width:100vw;max-width:100vw;max-height:85dvh;margin:auto 0 0;border-radius:20px 20px 0 0}.dialog-body{padding-bottom:max(20px,env(safe-area-inset-bottom))}}
`;
export const EDITOR_STYLE = `
:host ha-selector{display:block;width:100%}
:host{display:block;color:var(--primary-text-color);font-family:var(--ha-font-family-body,inherit)}*{box-sizing:border-box}.editor{padding:4px 0}.field{display:block;margin:0 0 16px}.label{display:block;font-size:13px;font-weight:500;margin-bottom:6px}select,input{width:100%;min-height:44px;border:1px solid var(--divider-color,#aaa);border-radius:8px;background:var(--card-background-color,#fff);color:var(--primary-text-color,#222);padding:10px 12px;font:inherit}select:focus-visible,input:focus-visible,button:focus-visible{outline:2px solid var(--primary-color,#03a9f4);outline-offset:2px}select:disabled{opacity:.6}.hint{font-size:12px;color:var(--secondary-text-color,#666);line-height:1.5;margin:6px 0 16px}.slots{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.section-title{font-size:14px;font-weight:600;margin:18px 0 12px}.reset{border:0;background:none;padding:4px 0;color:var(--primary-color,#03a9f4);cursor:pointer;font:inherit;font-size:13px}.advanced{margin-top:20px;border-top:1px solid var(--divider-color,#ddd);padding-top:16px}.advanced>summary{cursor:pointer;font-size:14px;padding-bottom:16px}select[multiple]{min-height:130px}.error{color:var(--error-color,#db4437);font-size:13px}.error:empty{display:none}.unit-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field small{font-size:12px;color:var(--secondary-text-color,#666)}
.exclusions{border-top:1px solid var(--divider-color,#ddd);padding-top:4px}.exclusions summary,.specific-entities summary{cursor:pointer;min-height:44px;padding:12px 0;font-size:14px}.exclusions>summary{font-weight:500}.exclusion-count{display:inline-block;margin-left:8px;font-size:12px;font-weight:400;color:var(--secondary-text-color,#666)}.exclusion-list .field{margin:0 0 8px}.exclusion-options{max-height:320px;overflow:auto;overscroll-behavior:contain}.exclusion-option{display:flex;gap:12px;align-items:center;min-height:56px;padding:8px 2px;border-bottom:1px solid var(--divider-color,#ddd);cursor:pointer}.exclusion-option[hidden],.exclusion-empty[hidden]{display:none}.exclusion-option input[type=checkbox]{appearance:auto;width:18px;height:18px;min-height:18px;margin:0;padding:0;flex:0 0 18px;accent-color:var(--primary-color,#03a9f4);cursor:inherit}.exclusion-option:has(input:disabled){opacity:.65;cursor:default}.exclusion-text{min-width:0}.exclusion-name,.exclusion-detail{display:block;overflow-wrap:anywhere}.exclusion-name{font-size:14px}.exclusion-detail{font-size:12px;color:var(--secondary-text-color,#666)}.specific-entities{margin-top:12px}input[type=search]{font-size:16px}.exclusion-empty{padding:8px 0}
`;
